//go:build !ignore_autogenerated

// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootServiceSpec) DeepCopyInto(out *BootServiceSpec) {
	*out = *in
	in.ServiceDefaults.DeepCopyInto(&out.ServiceDefaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootServiceSpec.
func (in *BootServiceSpec) DeepCopy() *BootServiceSpec {
	if in == nil {
		return nil
	}
	out := new(BootServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDHCPSpec) DeepCopyInto(out *CoreDHCPSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LeaseRanges != nil {
		in, out := &in.LeaseRanges, &out.LeaseRanges
		*out = make([]DHCPLeaseRange, len(*in))
		copy(*out, *in)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDHCPSpec.
func (in *CoreDHCPSpec) DeepCopy() *CoreDHCPSpec {
	if in == nil {
		return nil
	}
	out := new(CoreDHCPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPLeaseRange) DeepCopyInto(out *DHCPLeaseRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPLeaseRange.
func (in *DHCPLeaseRange) DeepCopy() *DHCPLeaseRange {
	if in == nil {
		return nil
	}
	out := new(DHCPLeaseRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayStatus.
func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagesSpec) DeepCopyInto(out *ImagesSpec) {
	*out = *in
	if in.Pinned != nil {
		in, out := &in.Pinned, &out.Pinned
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagesSpec.
func (in *ImagesSpec) DeepCopy() *ImagesSpec {
	if in == nil {
		return nil
	}
	out := new(ImagesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingSpec) DeepCopyInto(out *LoggingSpec) {
	*out = *in
	if in.IncludeServices != nil {
		in, out := &in.IncludeServices, &out.IncludeServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.CompactorImage != nil {
		in, out := &in.CompactorImage, &out.CompactorImage
		*out = new(ImageSpec)
		**out = **in
	}
	if in.QueryImage != nil {
		in, out := &in.QueryImage, &out.QueryImage
		*out = new(ImageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingSpec.
func (in *LoggingSpec) DeepCopy() *LoggingSpec {
	if in == nil {
		return nil
	}
	out := new(LoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagellanSpec) DeepCopyInto(out *MagellanSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagellanSpec.
func (in *MagellanSpec) DeepCopy() *MagellanSpec {
	if in == nil {
		return nil
	}
	out := new(MagellanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataServiceSpec) DeepCopyInto(out *MetadataServiceSpec) {
	*out = *in
	in.ServiceDefaults.DeepCopyInto(&out.ServiceDefaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataServiceSpec.
func (in *MetadataServiceSpec) DeepCopy() *MetadataServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbeSpec) DeepCopyInto(out *NetworkProbeSpec) {
	*out = *in
	if in.ProvisionNetwork != nil {
		in, out := &in.ProvisionNetwork, &out.ProvisionNetwork
		*out = new(NetworkProbeTarget)
		**out = **in
	}
	if in.BMCNetwork != nil {
		in, out := &in.BMCNetwork, &out.BMCNetwork
		*out = new(NetworkProbeTarget)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbeSpec.
func (in *NetworkProbeSpec) DeepCopy() *NetworkProbeSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbeStatus) DeepCopyInto(out *NetworkProbeStatus) {
	*out = *in
	if in.NodesWithProvisionAccess != nil {
		in, out := &in.NodesWithProvisionAccess, &out.NodesWithProvisionAccess
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodesWithBMCAccess != nil {
		in, out := &in.NodesWithBMCAccess, &out.NodesWithBMCAccess
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbeStatus.
func (in *NetworkProbeStatus) DeepCopy() *NetworkProbeStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbeTarget) DeepCopyInto(out *NetworkProbeTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbeTarget.
func (in *NetworkProbeTarget) DeepCopy() *NetworkProbeTarget {
	if in == nil {
		return nil
	}
	out := new(NetworkProbeTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkingSpec) DeepCopyInto(out *NetworkingSpec) {
	*out = *in
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkingSpec.
func (in *NetworkingSpec) DeepCopy() *NetworkingSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSpec) DeepCopyInto(out *ObjectStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSpec.
func (in *ObjectStorageSpec) DeepCopy() *ObjectStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenCHAMIControlPlane) DeepCopyInto(out *OpenCHAMIControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenCHAMIControlPlane.
func (in *OpenCHAMIControlPlane) DeepCopy() *OpenCHAMIControlPlane {
	if in == nil {
		return nil
	}
	out := new(OpenCHAMIControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenCHAMIControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenCHAMIControlPlaneList) DeepCopyInto(out *OpenCHAMIControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenCHAMIControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenCHAMIControlPlaneList.
func (in *OpenCHAMIControlPlaneList) DeepCopy() *OpenCHAMIControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(OpenCHAMIControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenCHAMIControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenCHAMIControlPlaneSpec) DeepCopyInto(out *OpenCHAMIControlPlaneSpec) {
	*out = *in
	in.Platform.DeepCopyInto(&out.Platform)
	in.NetworkProbe.DeepCopyInto(&out.NetworkProbe)
	in.Services.DeepCopyInto(&out.Services)
	out.Networking = in.Networking
	in.Database.DeepCopyInto(&out.Database)
	in.Logging.DeepCopyInto(&out.Logging)
	out.Observability = in.Observability
	in.Images.DeepCopyInto(&out.Images)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenCHAMIControlPlaneSpec.
func (in *OpenCHAMIControlPlaneSpec) DeepCopy() *OpenCHAMIControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(OpenCHAMIControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenCHAMIControlPlaneStatus) DeepCopyInto(out *OpenCHAMIControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make(map[string]ServiceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkProbe != nil {
		in, out := &in.NetworkProbe, &out.NetworkProbe
		*out = new(NetworkProbeStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenCHAMIControlPlaneStatus.
func (in *OpenCHAMIControlPlaneStatus) DeepCopy() *OpenCHAMIControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(OpenCHAMIControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSpec) DeepCopyInto(out *PlatformSpec) {
	*out = *in
	in.Vault.DeepCopyInto(&out.Vault)
	out.ObjectStorage = in.ObjectStorage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSpec.
func (in *PlatformSpec) DeepCopy() *PlatformSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMDSpec) DeepCopyInto(out *SMDSpec) {
	*out = *in
	in.ServiceDefaults.DeepCopyInto(&out.ServiceDefaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMDSpec.
func (in *SMDSpec) DeepCopy() *SMDSpec {
	if in == nil {
		return nil
	}
	out := new(SMDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDefaults) DeepCopyInto(out *ServiceDefaults) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	out.TLS = in.TLS
	if in.ExternalEndpoint != nil {
		in, out := &in.ExternalEndpoint, &out.ExternalEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDefaults.
func (in *ServiceDefaults) DeepCopy() *ServiceDefaults {
	if in == nil {
		return nil
	}
	out := new(ServiceDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTLSConfig) DeepCopyInto(out *ServiceTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTLSConfig.
func (in *ServiceTLSConfig) DeepCopy() *ServiceTLSConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesSpec) DeepCopyInto(out *ServicesSpec) {
	*out = *in
	in.SMD.DeepCopyInto(&out.SMD)
	in.Tokensmith.DeepCopyInto(&out.Tokensmith)
	in.BootService.DeepCopyInto(&out.BootService)
	in.MetadataService.DeepCopyInto(&out.MetadataService)
	in.CoreDHCP.DeepCopyInto(&out.CoreDHCP)
	in.Magellan.DeepCopyInto(&out.Magellan)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesSpec.
func (in *ServicesSpec) DeepCopy() *ServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokensmithSpec) DeepCopyInto(out *TokensmithSpec) {
	*out = *in
	in.ServiceDefaults.DeepCopyInto(&out.ServiceDefaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokensmithSpec.
func (in *TokensmithSpec) DeepCopy() *TokensmithSpec {
	if in == nil {
		return nil
	}
	out := new(TokensmithSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSpec) DeepCopyInto(out *VaultSpec) {
	*out = *in
	if in.AppRoleSecretRef != nil {
		in, out := &in.AppRoleSecretRef, &out.AppRoleSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSpec.
func (in *VaultSpec) DeepCopy() *VaultSpec {
	if in == nil {
		return nil
	}
	out := new(VaultSpec)
	in.DeepCopyInto(out)
	return out
}
