// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package reconcilers

import (
	"fmt"
	"net"
	"strings"

	openchamiv1alpha1 "github.com/openchami/openchami-operator/api/v1alpha1"
)

// renderCoreDHCPConfig produces the YAML config consumed by the upstream
// coredhcp binary. The format matches coredhcp's `server4:` schema (one
// listener, an ordered plugin list).
//
// We deliberately keep this rendering inside the operator instead of an
// init-container shell template: the inputs are already typed in the CRD
// (`spec.services.coreDHCP.leaseRanges`) and the output is a small static
// file. An init-container would add a second image to the supply chain
// without changing what's being expressed.
//
// Multi-subnet limitation: coredhcp's `server4` block has one plugin chain.
// True multi-subnet service requires per-listener subnet selection, which
// the upstream image does not support cleanly. We render the **first**
// lease range and emit a TODO comment for the rest. The webhook validation
// already requires `len(leaseRanges) >= 1` when CoreDHCP is enabled, so
// the slice is never empty here.
func renderCoreDHCPConfig(cp *openchamiv1alpha1.OpenCHAMIControlPlane) (string, error) {
	dhcp := cp.Spec.Services.CoreDHCP
	if len(dhcp.LeaseRanges) == 0 {
		return "", fmt.Errorf("coredhcp: at least one leaseRange required")
	}
	r := dhcp.LeaseRanges[0]

	_, ipnet, err := net.ParseCIDR(r.Subnet)
	if err != nil {
		return "", fmt.Errorf("coredhcp: invalid subnet %q: %w", r.Subnet, err)
	}
	netmask := net.IP(ipnet.Mask).To4()
	if netmask == nil {
		return "", fmt.Errorf("coredhcp: only IPv4 subnets are supported, got %q", r.Subnet)
	}
	// First usable host address — assume gateway/server-id sit at .1 of
	// the subnet. This matches the typical HPC provisioning convention
	// (head node serves DHCP from the .1 of the provision network) and
	// keeps the operator from needing yet another CRD field. Operators
	// who want a non-conventional gateway can override the rendered
	// ConfigMap out-of-band; the field manager check will not stomp it.
	gateway := firstUsableIPv4(ipnet)
	if gateway == nil {
		return "", fmt.Errorf("coredhcp: subnet %q has no usable host addresses", r.Subnet)
	}

	known := dhcp.KnownLeaseDuration
	if known == "" {
		known = "1h"
	}
	unknown := dhcp.UnknownLeaseDuration
	if unknown == "" {
		unknown = "5m"
	}

	var b strings.Builder
	b.WriteString("# Generated by openchami-operator. Do not edit by hand.\n")
	b.WriteString("# Cluster: " + cp.Spec.ClusterName + "\n")
	if len(dhcp.LeaseRanges) > 1 {
		fmt.Fprintf(&b,
			"# WARNING: %d additional leaseRanges ignored — coredhcp's server4\n"+
				"# block supports a single plugin chain. Track upstream multi-subnet\n"+
				"# support before adding more here.\n", len(dhcp.LeaseRanges)-1)
	}
	b.WriteString("server4:\n")
	b.WriteString("  listen:\n")
	b.WriteString("    - \"0.0.0.0:67\"\n")
	b.WriteString("  plugins:\n")
	fmt.Fprintf(&b, "    - lease_time: %s\n", known)
	fmt.Fprintf(&b, "    - server_id: %s\n", gateway.String())
	fmt.Fprintf(&b, "    - dns: 1.1.1.1 8.8.8.8\n")
	fmt.Fprintf(&b, "    - router: %s\n", gateway.String())
	fmt.Fprintf(&b, "    - netmask: %s\n", netmask.String())
	// Lease DB lives under /tmp because that's the only writable mount on
	// the pod (emptyDir from TmpVolume()). Lease data is naturally
	// regenerated as DHCPDISCOVERs come in, so emptyDir's per-pod
	// lifetime is acceptable. A persistent hostPath or PVC would be
	// required only if a deployment needs lease continuity across pod
	// restarts — that's a deployment-policy decision, not the operator's.
	fmt.Fprintf(&b, "    - range: /tmp/coredhcp-leases.txt %s %s %s\n",
		r.Start, r.End, unknown)
	return b.String(), nil
}

// firstUsableIPv4 returns the first host address in an IPv4 CIDR (.1 in a
// /24, etc.). Returns nil for /32 (no host range) or non-IPv4 networks.
func firstUsableIPv4(ipnet *net.IPNet) net.IP {
	ip := ipnet.IP.To4()
	if ip == nil {
		return nil
	}
	ones, bits := ipnet.Mask.Size()
	if bits != 32 || ones >= 31 {
		return nil
	}
	out := make(net.IP, 4)
	copy(out, ip)
	out[3]++
	return out
}
